### PR TITLE
Redesign the UI

### PR DESCRIPTION
**Pull request by jonatanklosko**
It's purely design change, so just check out how everything looks locally. Let me know what you think, which parts you like/not like.

I tried using `classes` whenever possible, but also used some inline styles in class components (as converting them to hooks would result in even bigger diff, I can do so separately if you think it's worth it ^^).

### CODE REVIEW

**Comment by jonatanklosko** [comment]
Ping :smiley:

**Comment by viroulep** [comment]
I like very much what you've done!
The only thing I would change is the default tab shown: since cubecomps and xlsx are still widely spread, I'd put the "upload xlsx" tab as the default tab (then the sign in with WCA, then the upload wcif).
Obviously as time goes by it's very likely that the default tab will end up being the "sign in" one :)

**Comment by jonatanklosko** [comment]
Actually the reason why I put WCA import first is that when you click sign in, you're redirected back to the home page and it would be confusing not to show competition list in that case. One idea would be placing WCA import second, but activate it initially if the user is signed in. Thoughts?

**Comment by viroulep** [comment]
Ah good point!
Yes when logged in it's absolutely the WCA import which should be active by default, that's the only point of being logged in :D

I think the behavior you describe (load xslx tab active first when not logged in, load from WCA active if logged in) is what we should do.

**Comment by jonatanklosko** [comment]
Done!

**Comment by viroulep** [comment]
Thanks!

**Pull request merged**
